maint: suppress a false-positive -Wcast-align warning
Building with --enable-gcc-warnings and gcc-4.9.1 would provoke this:
  grep.c:499:12: error: cast from 'const char *' to 'const uword *'\
      (aka 'const unsigned long *') increases required alignment from\
      1 to 8 [-Werror,-Wcast-align]
    for (s = (uword const *) p; ! (*s & hibyte_mask); s++)
	     ^~~~~~~~~~~~~~~~~
* src/grep.c (skip_easy_bytes): Use a pragma to suppress
gcc's false-positive cast-alignment warning.