build: link with -lsigsegv, when c-stack module requires it
* src/Makefile.am (grep_LDADD): Add $(LIBCSTACK).
Otherwise, on at least Debian and Arch-based systems, linking would
fail with diagnostics like these:
  c-stack.c:207: undefined reference to `stackoverflow_install_handler'
  c-stack.c:216: undefined reference to `sigsegv_install_handler'
Reported by Jeremy Feusi.